name: Admin UI Build and Publish
on:
  push:
    branches:
      - dev
env:
  AWS_REGION: 'us-east-1'
  AWS_S3_BUCKET: 'velo-fineractui-dev'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag community:latest
    - name: Run docker container
      run: |
        docker run -d -p 80:80 --name communityui community:latest
        mkdir build
        docker cp communityui:/usr/share/nginx/html ./build/
        docker stop communityui
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Deploy static site to S3 bucket
      run: |
        aws s3 sync ./build/html s3://${{ env.AWS_S3_BUCKET }} --delete
